name: Secure CI Pipeline (Juice Shop)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # فحص التبعيات
    - name: Run npm audit
      run: npm audit --audit-level=low

    # فحص جودة الكود
    - name: Run ESLint
      run: |
        npx eslint . || true

    # فحص الأسرار داخل الكود
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: ""
        fail: false

    # فحص التبعيات باستخدام Snyk
    - name: Snyk Scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    # فحص الكود الثابت (Static Analysis) باستخدام Semgrep
    - name: Run Semgrep Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/javascript"

    # فحص أكواد JavaScript لكشف ثغرات OWASP
    - name: Detect OWASP Issues in JS (js-xss)
      run: |
        npm install -g js-xss
        grep -r --include \*.js "innerHTML\|document.write\|eval\|Function(" . || true
